version: '2'
services:
  web:
    image: node:8.9
    command: node ./server.js
    working_dir: /usr/src/scrapper
    volumes:
      - .:/usr/src/scrapper
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
      container_name: mongo
      image: mongo
      volumes:
        - ./data:/data/db
      ports:
        - "27017:27017"